### ISSUE TITLE
Strange behavior

### ISSUE THREAD

**Issue by HenriqueMonte** [APISENSE/rhino-android#7]
Some numbers starting with 0 cause strange behavior in the calculation. 
Examples: 
eval(016+2) returns 16.
eval(016) returns 14
eval(031) returns 25
eval(031x2) returns 50

Other examples looks ok:
eval(018+2) returns 20.
eval(019+5) returns 24.

What could be happening?

**Comment by aveuiller** [comment]
Hello,

In JavaScript, putting a 0 in front of an integer will cast it to octal, as well as 0x will cast it as hexadecimal and 0b as binary.

This behavior does not take place if there is an 8 or a 9 in your integer since the cast to octal is impossible in this case.

So the behavior here seems completely normal for JavaScript ;)

**Comment by HenriqueMonte** [comment]
Thank you. So I need to treat my expression to avoid this.
